# Generated by Django 5.0 on 2023-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('textbox', models.CharField(choices=[('Missing/Broken/Wrong Item', 'Missing/Broken/Wrong Item'), ('Delayed Delivery', 'Delayed Delivery'), ('Exchange/Return Order', 'Exchange/Return Order'), ('Delivery Related Complaint', 'Delivery Related Complaint'), ('Other', 'Other')], max_length=122)),
                ('other_details', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
