# Generated by Django 5.0 on 2023-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_details',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
    ]
