# Generated by Django 5.0 on 2023-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_other_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newEmail', models.CharField(max_length=50)),
                ('newPassword', models.CharField(max_length=122)),
            ],
        ),
    ]
